server:
  port: 18082
  
spring:
  rabbitmq:
    template:
      retry:
        enabled: true
        max-attempts: 5
    host: localhost
    port: 5672
    addresses: localhost:5672
    virtual-host: /
    username: admin
    password: admin
    dynamic: true
    cache:
      connection:
        mode: connection
    listener:
      simple:
        auto-startup: true
        acknowledge-mode: auto
        
hazelcast:
  config:
    group:
      name: vehicles
      password: Tb4
    network:
      port: 5705
      port-auto-increment: true
      multicast:
        enabled: true
        interfaces: false
        port: 6566
        group: group
        loopback-mode: false
      tcp-ip.enabled: true
      tcp-ip.members: 127.0.0.1