server:
  port: 18083

spring:
  rabbitmq:
    template:
      retry:
        enabled: true
        max-attempts: 5
    host: localhost
    port: 5672
    addresses: localhost:5672
    virtual-host: /
    username: admin
    password: admin
    dynamic: true
    cache:
      connection:
        mode: connection
    listener:
      simple:
        auto-startup: true
        acknowledge-mode: auto
    
    
vehicles:
  mq:
    consumer:
      queue:
        size: 200
  automata:
    script:
      - initial->CREATE:created,PAUSE:initial,FINISH:initial,MOVE_UP:initial,MOVE_DOWN:initial,MOVE_LEFT:initial,MOVE_RIGHT:initial
      - created->PAUSE:created,CREATE:created,FINISH:end,MOVE_UP:Moving_Up,MOVE_DOWN:Moving_Down,MOVE_LEFT:Moving_Left,MOVE_RIGHT:Moving_Right
      - Moving_Up->PAUSE:created,CREATE:Moving_Up,FINISH:end,MOVE_UP:Moving_Up,MOVE_DOWN:Moving_Down,MOVE_LEFT:Moving_Left,MOVE_RIGHT:Moving_Right
      - Moving_Down->PAUSE:created,CREATE:Moving_Down,FINISH:end,MOVE_UP:Moving_Up,MOVE_DOWN:Moving_Down,MOVE_LEFT:Moving_Left,MOVE_RIGHT:Moving_Right
      - Moving_Left->PAUSE:created,CREATE:Moving_Left,FINISH:end,MOVE_UP:Moving_Up,MOVE_DOWN:Moving_Down,MOVE_LEFT:Moving_Left,MOVE_RIGHT:Moving_Right
      - Moving_Right->PAUSE:created,CREATE:Moving_Right,FINISH:end,MOVE_UP:Moving_Up,MOVE_DOWN:Moving_Down,MOVE_LEFT:Moving_Left,MOVE_RIGHT:Moving_Right
      - End->

hazelcast:
  config:
    group:
      name: vehicles
      password: Tb4
    network:
      port: 5705
      port-auto-increment: true
      multicast:
        enabled: true
        interfaces: false
        port: 6566
        group: group
        loopback-mode: false
      tcp-ip.enabled: true
      tcp-ip.members: 127.0.0.1