version: '2.1'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15672:15672"
      - "5672:5672"

  tbaconsumer:
    image: tbaconsumer
    container_name: tbaconsumer
    depends_on:
      - rabbitmq

  tbawebsocket:
    image: tbawebsocket
    container_name: tbawebsocket
    depends_on:
      - rabbitmq
    ports:
      - "8080:18082"
    expose:
      - "8080"

  tbafrontend:
    image: tbafrontend
    container_name: tbafrontend
    depends_on:
      - tbawebsocket
    ports:
      - "9000:80"
      
networks: 
  default:
    external:
      name: ci_vpc